# Generated by Django 2.1.2 on 2019-05-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0002_auto_20190530_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='folder_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='protocol_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
