# Generated by Django 2.1.2 on 2019-05-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '__first__'),
        ('authapi', '0003_auto_20190530_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vocab_list',
            field=models.ManyToManyField(to='vocab.Vocabs'),
        ),
    ]
