# Generated by Django 2.1.5 on 2019-02-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabs',
            name='german',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
