# Generated by Django 2.1.2 on 2019-06-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_userdummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdummy',
            name='vocabList',
        ),
        migrations.AlterField(
            model_name='vocabs',
            name='german',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='UserDummy',
        ),
    ]
