# Generated by Django 3.0 on 2020-02-24 09:38

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0007_vocabs_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabs',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/vocab/', location='C:\\WebDev Projects\\language_site\\backend\\media/vocab/'), upload_to='media'),
        ),
    ]
